### ISSUE TITLE
JLCPCB makes it look like the pick and place locations are incorrect in the current CPL file

### ISSUE THREAD

**Issue by darraghbr** [drspangle/infidel-sensor#11] opened 2021-03-07 20:43 UTC
If you go through the order process with JLCPCB the resulting pick and place locations are incorrect.

![image](https://user-images.githubusercontent.com/31858409/110254156-ceb0c000-7f85-11eb-861a-5e3594d222c0.png)

JLCPCB will still accept the files and it should work properly, they go through a checking process where they will adjust the positions by hand.

**Comment by drspangle** [comment] 2021-03-07 21:14
So is the issue that the pad placement for the IC3 chip and the other SMD component is incorrect, or is there a deeper issue here? I'm not seeing precisely what the issue is. Does this screenshot come from JLCPCB's design checker?

**Comment by darraghbr** [comment] 2021-03-07 23:19
I think it's a JLC issue, I've checked and double checked the positions and it just seems the presence of the switch in the CPL file breaks everything.

**Comment by blurfl** [comment] 2021-03-07 23:57
We shouldn't modify our BOM to work around one vendor's internal issue. They correct for it when they review the order.

**Comment by midopple** [comment] 2021-03-08 21:12
I had the same problem with JLCPCB, after contacting support I was told that this is due to the web preview and is still being checked before the production process.

**Comment by electrickery** [comment] 2021-03-20 14:09
My boards arrives some days ago and the components are all at the right places. Haven't started and programmed the board yet.

**Comment by coelholm** [comment] 2021-04-09 00:56
I saw same issue. It is an issue with JLCPCB web preview. I have tried to correct placement position of each component one by one (It was looking fine), but when I got to the last component, everything looked "misaligned" again, so I decided to use original file and my boards are perfect.

**Comment by drspangle** [comment] 2021-04-16 07:03
It seems like this isn't actually an issue, rather is a problem on JLCPCB's end. I'll close this now.

**Closed by drspangle** 2021-04-16 07:03 UTC
